### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by SethuSenthil** [Rawnly/OSX-SETUP#1]
The installer doesn't work? Am I doing something wrong?
Info:
MacOS mojave 

Error Logs:
    /Users/sethu/Downloads/dot-files-master/setup_macos.sh: line 26: syntax error near unexpected token `command'
    /Users/sethu/Downloads/dot-files-master/setup_macos.sh: line 26: `command -v zsh >/dev/null 2>&1 || installZSH()'

**Comment by rawnly** [comment]
I’ll fix this soon as possibile, in the meantime you can install it manually
